apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-woq0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-woq0@sha256:f27b94cb39d2cf316f755105362f8aa1d8c81aa4684ea086303b571d51db577e
        name: my-nodejs
        resources: {}
status: {}
